### ISSUE TITLE
"index out of range" with dynamic array size

### ISSUE THREAD

**Issue by Ketec** [jDataView/jBinary#65]
I add new elements to the data i read in but on save i get the "index out of range" error when i call writeAll(data).

"array(baseType, @length) - array of given type and length, reads/writes to the end of binary if length is not given."
I did not specify length. So i assumed it would be able to still save if i add more entries to the array than there was before - but it only works if i remove or keep the number the same.

```
    file: {
        recordNum: "int32",
        fieldNum: "int32",
        recordSize: "int32",
        data: ["array", dataFld"]
    }
```
```

RangeError: Index out of range
    at checkInt (buffer.js:1187:11)
    at Buffer.writeInt32LE (buffer.js:1375:5)
```

I store the jbinary object:
```
            loadedJBinary = binary;
            resolve({ data: loadedJBinary.readAll() });
```
And use it again to write:
`loadedJBinary.writeAll(data);`

Because i saw no way to use a existing js object to create a new jBinary object to save.
But this does not work with the increasing array size.

Nether did i find any way to update the size of arrays before writeall.

 Can just hope this project isn't dead, it's the only one in existence that i could find that allows use of a C++ like struct approach.

**Comment by RReverser** [comment]
> Can just hope this project isn't dead

It's not :) There is lots of improvements that could be done, but I don't have time for, but maintenance-wise it's still very much supported. 

In your case the issue is that you did specify length, but to a non-existent field, so it tried to use it, but failed. If you omit that length parameter, it should work as expected, and read/write array without bounds.

Also note that your array type must have a base type as well, otherwise it's unclear what type of items you're expecting.

**Comment by Ketec** [comment]
`data: ["array", dataFld"] ` has no length value

the array type is the default one provided by jBinary

It can read fine - for example 1500 dataFld objects.

But when  i  add one in js and on save it's 1501, the last one gives out of bounds error.

I did try custom type to debug:

```
    DynamicArray: jBinary.Template({
        params: ["baseType"],
        read: function() {
            let results;

            let end = this.view.byteLength;
            for (results = []; this.binary.tell() < end; ) {
                results.push(this.baseRead());
            }
            return results;
        },
        write: function(values) {
            for (let i = 0; values.length > i; i++) {
                 this.baseWrite(values[i]);
            }
        }
    }),
```
and it fails at 1501st item.

**Comment by RReverser** [comment]
Oh, right, I thought `dataFld` was a field name as it suggests, not a type name. Now I see that the problem is not the array type at all, it looks like it's instead coming from Buffer itself (as you can see from buffer.js in the stacktrace). Did you allocate a new buffer of sufficient size for writing data out? If not, that's the cause of the problem - you're trying to put a larger array into a Buffer that could hold only smaller one.

**Comment by Ketec** [comment]
Where would i do it in jBinary when i call for writeAll?

The only thing i saw was jBinary constructor that takes buffer size in bytes.  And i do not know the byte size of a js object (also because the null terminated strings are shorter and do not include the 00 bytes - so the string may only be 2 bytes in object but it should be 64 bytes in final data).

Is there a way to increase the buffer size by using a type (like adding x number of dataFld size).
Did not see a way to get the size of current buffer or get the size of type.
